enableTelemetry: false

nodeLinker: node-modules

nmSelfReferences: false

winLinkType: "symlinks"

npmScopes:
  "episerver":
    "npmRegistryServer": "https://pkgs.dev.azure.com/EpiserverEngineering/netCore/_packaging/HeadlessForms/npm/registry"

injectEnvironmentFiles:
  - ".env.yarn?"
  - ".env.yarn.local?"
